import { Building, Users, GraduationCap, Mic, Heart, Laptop } from "lucide-react";

export const SITE_CONFIG = {
  name: "TRCV",
  fullName: "The Red Carpet Ventures",
  tagline: "Corporate Event Planning Services in India",
  description: "TRCV is India's trusted corporate event planning company. We deliver seamless conferences, exhibitions, trainings, and AV production.",
  url: "https://trcv.in",
  email: "support@trcv.in",
  phone: "+91-9560200314",
  address: "614, Eros City Square, Gurugram, Haryana, India",
  
  stats: {
    events: "500+",
    cities: "50+",
    attendees: "100K+",
    satisfaction: "98%",
  },
  
  services: [
    {
      id: "corporate-events",
      title: "Corporate Events",
      description: "Annual meets, product launches, and celebrations tailored to your brand objectives.",
      icon: Building,
      features: ["Product Launches", "Annual Meetings", "Award Nights", "Team Building Events"],
      gradient: "from-trcv-orange to-trcv-pink",
    },
    {
      id: "training-workshops",
      title: "Trainings & Workshops",
      description: "Employee development and leadership sessions designed for skill-building and growth.",
      icon: GraduationCap,
      features: ["Leadership Development", "Skill Building Sessions", "Corporate Training", "Workshop Facilitation"],
      gradient: "from-trcv-purple to-trcv-blue",
    },
    {
      id: "av-production",
      title: "AV Production",
      description: "Sound, light, and stage setups for impactful and professional experiences.",
      icon: Mic,
      features: ["Professional Sound Systems", "Dynamic Lighting Setup", "Stage Design & Setup", "Live Streaming Solutions"],
      gradient: "from-trcv-emerald to-trcv-blue",
    },
    {
      id: "exhibitions-conferences",
      title: "Exhibitions & Conferences",
      description: "Trade shows, seminars, and business summits with comprehensive management.",
      icon: Users,
      features: ["Trade Shows", "Business Seminars", "Industry Summits", "Networking Events"],
      gradient: "from-trcv-amber to-trcv-orange",
    },
    {
      id: "weddings-special",
      title: "Weddings & Special Events",
      description: "Exclusive private celebrations and milestone events crafted with attention to detail.",
      icon: Heart,
      features: ["Wedding Planning", "Anniversary Celebrations", "Birthday Parties", "Private Functions"],
      gradient: "from-trcv-pink to-trcv-purple",
    },
    {
      id: "virtual-hybrid",
      title: "Virtual & Hybrid Events",
      description: "Digital experiences and hybrid solutions for modern corporate needs.",
      icon: Laptop,
      features: ["Virtual Conferences", "Hybrid Events", "Online Training Sessions", "Digital Engagement"],
      gradient: "from-trcv-blue to-indigo-600",
    },
  ],
  
  testimonials: [
    {
      id: 1,
      quote: "TRCV transformed our annual corporate meet into a seamless and engaging experience. Their team handled everything from planning to AV production flawlessly.",
      author: "HR Head",
      company: "IT Company, Gurugram",
      rating: 5,
    },
    {
      id: 2,
      quote: "We worked with TRCV for a product launch in Mumbai. The event was perfectly executed, and the AV production quality was top-notch.",
      author: "Marketing Manager",
      company: "FMCG Brand, Mumbai",
      rating: 5,
    },
    {
      id: 3,
      quote: "Our nationwide training rollout was managed brilliantly by TRCV. Every detail was taken care of, and the sessions were smooth and professional.",
      author: "L&D Manager",
      company: "Finance Company, Bengaluru",
      rating: 5,
    },
    {
      id: 4,
      quote: "Professional, reliable, and creative! TRCV helped us organize a high-profile business exhibition, and it was a great success.",
      author: "Event Head",
      company: "Trade Association, Delhi NCR",
      rating: 5,
    },
    {
      id: 5,
      quote: "TRCV's attention to detail and creative solutions made our corporate awards night absolutely memorable. Highly recommended!",
      author: "Communications Manager",
      company: "Tech Startup, Pune",
      rating: 5,
    },
    {
      id: 6,
      quote: "Working with TRCV was a game-changer for our international conference. They managed everything seamlessly across multiple cities.",
      author: "Operations Director",
      company: "Multinational Corp, Chennai",
      rating: 5,
    },
  ],
  
  faqItems: [
    {
      id: "faq1",
      question: "What types of corporate events does TRCV organize in India?",
      answer: "We specialize in corporate events, conferences, exhibitions, trainings, workshops, and AV production across India. Whether it's a small corporate gathering or a large-scale international conference, TRCV ensures seamless planning and execution.",
    },
    {
      id: "faq2",
      question: "Which cities in India does TRCV serve?",
      answer: "We are based in Gurugram, Delhi NCR, but we plan events across all major Indian cities including Mumbai, Bengaluru, Pune, Hyderabad, and Chennai.",
    },
    {
      id: "faq3",
      question: "How much does it cost to plan a corporate event in India?",
      answer: "The cost depends on the event type, venue, and requirements. TRCV provides customized pricing packages for corporate events, trainings, and conferences. Contact us for a detailed quote.",
    },
    {
      id: "faq4",
      question: "Do you handle both physical and hybrid events?",
      answer: "Yes, TRCV offers end-to-end solutions for physical, hybrid, and virtual corporate events with AV production, live-streaming, and digital engagement tools.",
    },
    {
      id: "faq5",
      question: "How early should I book TRCV for my event?",
      answer: "We recommend booking at least 4–6 weeks in advance to ensure venue availability and smooth coordination. However, we also manage short-notice events depending on requirements.",
    },
    {
      id: "faq6",
      question: "What makes TRCV different from other event planners in India?",
      answer: "TRCV combines strategic planning, creative execution, and reliable logistics. Our focus on corporate events, nationwide reach, and proven track record set us apart from generic event planners.",
    },
  ],
};

export const PORTFOLIO_ITEMS = [
  {
    id: 1,
    title: "Annual Conference",
    location: "Delhi NCR",
    description: "Managed logistics, AV production, and coordinated 1000+ delegates for a successful corporate annual conference.",
    tags: ["Conference", "1000+ Attendees"],
    color: "trcv-orange",
    image: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&h=400&fit=crop",
  },
  {
    id: 2,
    title: "Training Rollout",
    location: "Bengaluru",
    description: "Coordinated 15 workshops nationwide for comprehensive employee development and skills enhancement.",
    tags: ["Training", "15 Workshops"],
    color: "trcv-purple",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&h=400&fit=crop",
  },
  {
    id: 3,
    title: "Product Launch",
    location: "Mumbai",
    description: "Grand launch event with professional AV production and live streaming for nationwide audience reach.",
    tags: ["Product Launch", "Live Streaming"],
    color: "trcv-emerald",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=400&fit=crop",
  },
  {
    id: 4,
    title: "Trade Exhibition",
    location: "Pune",
    description: "Successfully managed a 3-day trade exhibition with 200+ exhibitors and thousands of visitors.",
    tags: ["Exhibition", "200+ Exhibitors"],
    color: "trcv-amber",
    image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=800&h=400&fit=crop",
  },
  {
    id: 5,
    title: "Awards Ceremony",
    location: "Hyderabad",
    description: "Elegant awards night with sophisticated staging and memorable experiences for all attendees.",
    tags: ["Awards Night", "Gala Event"],
    color: "trcv-pink",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&h=400&fit=crop",
  },
  {
    id: 6,
    title: "Team Building Retreat",
    location: "Chennai",
    description: "Multi-day corporate retreat focused on team bonding and leadership development activities.",
    tags: ["Team Building", "Corporate Retreat"],
    color: "trcv-blue",
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&h=400&fit=crop",
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    title: "Top Corporate Venues 2025",
    excerpt: "Discover the best corporate venues across India for your next event. From luxury hotels to convention centers, find the perfect space.",
    category: "Venue Guide",
    date: "Jan 15, 2025",
    image: "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?w=800&h=400&fit=crop",
    categoryColor: "trcv-orange",
  },
  {
    id: 2,
    title: "Planning a Conference in India",
    excerpt: "A comprehensive guide to organizing successful conferences in India, covering logistics, vendor management, and attendee engagement.",
    category: "Planning Tips",
    date: "Jan 12, 2025",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=400&fit=crop",
    categoryColor: "trcv-purple",
  },
  {
    id: 3,
    title: "Hybrid Events in India",
    excerpt: "Explore the future of corporate events with hybrid solutions that combine physical and virtual experiences seamlessly.",
    category: "Technology",
    date: "Jan 10, 2025",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=400&fit=crop",
    categoryColor: "trcv-emerald",
  },
  {
    id: 4,
    title: "Corporate Event Trends 2025",
    excerpt: "Stay ahead of the curve with the latest corporate event trends shaping the industry in India and globally.",
    category: "Trends",
    date: "Jan 8, 2025",
    image: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&h=400&fit=crop",
    categoryColor: "trcv-amber",
  },
  {
    id: 5,
    title: "AV Production Essentials",
    excerpt: "Master the art of AV production for corporate events with our comprehensive guide to sound, lighting, and visual excellence.",
    category: "AV Production",
    date: "Jan 5, 2025",
    image: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&h=400&fit=crop",
    categoryColor: "trcv-pink",
  },
  {
    id: 6,
    title: "Event Budget Management",
    excerpt: "Learn effective strategies for managing corporate event budgets and maximizing ROI for your organization's events.",
    category: "Budget Planning",
    date: "Jan 3, 2025",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    categoryColor: "trcv-blue",
  },
];
